### ISSUE TITLE
cannot start on an AWS ubuntu instance

### ISSUE THREAD

**Issue by BloodyNoah** [hashelq/osu-lazer-room-bot#1]
Hey the bot worked fine, when I ran it on my desktop.
I now made an AWS ubuntu instance but I get this error when trying to run:

```
file:///home/ubuntu/osu-lazer-room-bot/src/index.js:48
maxMapLength = process.env.LENGTH_MAX_SECS ?? StaticProvider.defaultMaxLength
^

SyntaxError: Unexpected token '?'
at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by hashelq** [comment]
Maybe the node version is wrong. I am running Node.js v16.16.0 on Ubuntu 20.04.5 LTS

**Comment by BloodyNoah** [comment]
> Maybe the node version is wrong. I am running Node.js v16.16.0 on Ubuntu 20.04.5 LTS

Yeah that is probably it, I used a Arch instance later and it worked fine on there, thanks for the help
