### ISSUE TITLE
Bot can't find new maps

### ISSUE THREAD

**Issue by BloodyNoah** [hashelq/osu-lazer-room-bot#2]
Hello
I let the bot run for a while, came back and saw that it couldnt find any new map for the person which played before. I joined and added a map on my own bc the room was empty. After I played the map the bot said: "Sorry, it takes too long to to find a map. Probably bc of diffs", I have diffs from 2.5-3.5 so this should not be a problem.
The logs are in the attached file.

Thanks for your help
[logs.txt](https://github.com/hashelq/osu-lazer-room-bot/files/9954780/logs.txt)

**Comment by BloodyNoah** [comment]
Also I often get this warning:

`WARN [20:34:10.092] (207776): No client method with the name 'UserBeatmapAvailabilityChanged' found.`

**Comment by hashelq** [comment]
> Also I often get this warning:
> 
> `WARN [20:34:10.092] (207776): No client method with the name 'UserBeatmapAvailabilityChanged' found.`

https://github.com/hashelq/osu-lazer-room-bot/commit/fffe2e9891aae2a69f3eb486c0ea1755f13af518

**Comment by hashelq** [comment]
I think this is an expected behavior because it is hard to get a random map in osu, it is not well documented but you can try to increase "mapSearchingTimeout" in src/static.js.

**Comment by BloodyNoah** [comment]
alright, thanks
